export const imageMap: Record<string, any> = {
  "airplane": require("../assets/word-images/airplane/airplane.jpg"),
  "arecanut": require("../assets/word-images/arecanut/arecanut.png"),
  "auto": require("../assets/word-images/auto/auto.jpg"),
  "bear": require("../assets/word-images/bear/bear.png"),
  "blackboard": require("../assets/word-images/blackboard/blackboard.jpg"),
  "boat": require("../assets/word-images/boat/boat.jpg"),
  "body": require("../assets/word-images/body/body.png"),
  "bus": require("../assets/word-images/bus/bus.png"),
  "cap": require("../assets/word-images/cap/cap.jpg"),
  "cat": require("../assets/word-images/cat/cat.jpg"),
  "chair": require("../assets/word-images/chair/chair.png"),
  "city": require("../assets/word-images/city/city.jpg"),
  "class": require("../assets/word-images/class/class.jpg"),
  "clock": require("../assets/word-images/clock/clock.jpg"),
  "clothing": require("../assets/word-images/clothing/clothing.jpg"),
  "coconut": require("../assets/word-images/coconut/coconut.png"),
  "crane": require("../assets/word-images/crane/crane.png"),
  "crow": require("../assets/word-images/crow/crow.png"),
  "dove": require("../assets/word-images/dove/dove.png"),
  "dress": require("../assets/word-images/dress/dress.jpg"),
  "eagle": require("../assets/word-images/eagle/eagle.png"),
  "egg": require("../assets/word-images/egg/egg.png"),
  "eggplant": require("../assets/word-images/eggplant/eggplant.png"),
  "elephant": require("../assets/word-images/elephant/elephant.png"),
  "fan": require("../assets/word-images/fan/fan.jpg"),
  "finger": require("../assets/word-images/finger/finger.jpg"),
  "fish": require("../assets/word-images/fish/fish.jpg"),
  "fox": require("../assets/word-images/fox/fox.jpg"),
  "ginger": require("../assets/word-images/ginger/ginger.jpg"),
  "goat": require("../assets/word-images/goat/goat.png"),
  "gooseberry": require("../assets/word-images/gooseberry/gooseberry.jpg"),
  "guava": require("../assets/word-images/guava/guava.png"),
  "hand": require("../assets/word-images/hand/hand.png"),
  "hawk": require("../assets/word-images/hawk/hawk.png"),
  "hijab": require("../assets/word-images/hijab/hijab.png"),
  "honey": require("../assets/word-images/honey/honey.png"),
  "hospital": require("../assets/word-images/hospital/hospital.png"),
  "ink": require("../assets/word-images/ink/ink.jpg"),
  "jackfruit": require("../assets/word-images/jackfruit/jackfruit.jpg"),
  "knife": require("../assets/word-images/knife/knife.jpg"),
  "ladder": require("../assets/word-images/ladder/ladder.png"),
  "larry": require("../assets/word-images/larry/larry.png"),
  "mango": require("../assets/word-images/mango/mango.png"),
  "market": require("../assets/word-images/market/market.jpg"),
  "mask": require("../assets/word-images/mask/mask.png"),
  "myna": require("../assets/word-images/myna/myna.png"),
  "papaya": require("../assets/word-images/papaya/papaya.jpeg"),
  "parrot": require("../assets/word-images/parrot/parrot.png"),
  "pen": require("../assets/word-images/pen/pen.jpg"),
  "pencil": require("../assets/word-images/pencil/pencil.jpg"),
  "pepper": require("../assets/word-images/pepper/pepper.png"),
  "pig": require("../assets/word-images/pig/pig.png"),
  "pomegranate": require("../assets/word-images/pomegranate/pomegranate.jpg"),
  "quill": require("../assets/word-images/quill/quill.jpg"),
  "rambutan": require("../assets/word-images/rambutan/rambutan.jpg"),
  "rice": require("../assets/word-images/rice/rice.png"),
  "rooster": require("../assets/word-images/rooster/rooster.png"),
  "sandal": require("../assets/word-images/sandal/sandal.png"),
  "saree": require("../assets/word-images/saree/saree.png"),
  "snake": require("../assets/word-images/snake/snake.jpg"),
  "soil": require("../assets/word-images/soil/soil.jpg"),
  "stone": require("../assets/word-images/stone/stone.jpg"),
  "street": require("../assets/word-images/street/street.png"),
  "swing": require("../assets/word-images/swing/swing.png"),
  "tea": require("../assets/word-images/tea/tea.jpg"),
  "the cloud": require("../assets/word-images/the cloud/the cloud.jpg"),
  "the cow": require("../assets/word-images/the cow/the cow3.png"),
  "the dog": require("../assets/word-images/the dog/the dog.jpg"),
  "the eye": require("../assets/word-images/the eye/the eye.png"),
  "the face": require("../assets/word-images/the face/the face.jpg"),
  "the forest": require("../assets/word-images/the forest/the forest.png"),
  "the head": require("../assets/word-images/the head/the head.png"),
  "the lion": require("../assets/word-images/the lion/the lion.png"),
  "the moon": require("../assets/word-images/the moon/the moon.png"),
  "the mouth": require("../assets/word-images/the mouth/the mouth.jpg"),
  "the rain": require("../assets/word-images/the rain/the rain.jpg"),
  "the sea": require("../assets/word-images/the sea/the sea.jpg"),
  "the ship": require("../assets/word-images/the ship/the ship.png"),
  "the sky": require("../assets/word-images/the sky/the sky.jpg"),
  "the sun": require("../assets/word-images/the sun/the sun.png"),
  "thunder": require("../assets/word-images/thunder/thunder.jpg"),
  "tiger": require("../assets/word-images/tiger/tiger.jpg"),
  "tomato": require("../assets/word-images/tomato/tomato.png"),
  "tooth": require("../assets/word-images/tooth/tooth.jpg"),
  "town": require("../assets/word-images/town/town.jpg"),
  "tree": require("../assets/word-images/tree/tree.jpg"),
  "university": require("../assets/word-images/university/university.jpg"),
  "van": require("../assets/word-images/van/van.png"),
  "water": require("../assets/word-images/water/water.png"),
  "yogurt": require("../assets/word-images/yogurt/yogurt.png"),
};
